# The address to serve from.
addr = "127.0.0.1:3000"
# Delay all responses by a given number of milliseconds to simulate a
# high-latency connection while testing locally.
# latency = 200

# Defaults for certain parameters that can be configured at runtime.
[runtime]
# How frequently do we reload templates? If zero, then never.
template-refresh = 4
# From what file do we read the simulation code?
sim-file = "0.lua"
# How frequently do we run the simulation? If zero, then never.
sim-rate = 15

# The paths to directories where certain files are found and stored.
[paths]
# Blog manifest file.
blog = "Blog.toml"
# Renderer files.
render = "render"
# Simulation files.
sim = "sim"
# State files.
state = "state"
# Templates that aren't part of the renderer.
templates = "../templates"
# Static files.
static = "../static"

# Various other parameters relating to authentication.
[security]
# For how many seconds is a login challenge token considered valid?
auth-timeout = 240
# How frequently do we sweep the login challenge token list for outdated entries?
auth-sweep = 60
