[[posts]]
title = "We now have a blog!"
id = "hello_world"
date = "2020-05-29"

[[posts]]
title = "Admin controls"
id = "admin_controls"
date = "2020-06-02"

[[posts]]
title = "Improving the performance and flexibility of the design"
id = "serial_ecs"
date = "2020-06-13"
